version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smart-canteen-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: smart_canteen
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
